# Generated by Django 5.2 on 2025-05-07 21:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("id_article", models.AutoField(primary_key=True, serialize=False)),
                ("status", models.BooleanField(default=True, verbose_name="Publier ?")),
                (
                    "titre",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Titre de l'article"
                    ),
                ),
                ("slug", models.SlugField(default="", max_length=150)),
                ("lead", models.CharField(max_length=150, verbose_name="lead text")),
                ("content", models.TextField(verbose_name="Contenu principal")),
                (
                    "cover",
                    models.ImageField(
                        upload_to="Article_cover_image/",
                        verbose_name="Image de couverture",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="Article_main_image/", verbose_name="Image principal"
                    ),
                ),
                (
                    "cover_alt_text",
                    models.CharField(
                        max_length=125,
                        verbose_name="Texte alternatif pour accessibilité de l'image de couverture",
                    ),
                ),
                (
                    "image_alt_text",
                    models.CharField(
                        max_length=125,
                        verbose_name="Texte alternatif pour accessibilité de l'image principal",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date Création"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="chambre",
            fields=[
                ("id_chambre", models.AutoField(primary_key=True, serialize=False)),
                (
                    "prix_nuit",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Prix chambre"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="Chambre_image/", verbose_name="Image chambre"
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Description"),
                ),
                ("nombre_lit", models.IntegerField(verbose_name="Nombre de lit")),
                ("libre", models.BooleanField(default=True, verbose_name="Libre ?")),
                (
                    "is_best",
                    models.BooleanField(default=False, verbose_name="Meilleur offre ?"),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date Création"
                    ),
                ),
                (
                    "date_update",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2025, 5, 7, 21, 23, 25, 154297, tzinfo=datetime.timezone.utc
                        ),
                        verbose_name="Date Mise à jour",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContactCompany",
            fields=[
                ("id_contact", models.AutoField(primary_key=True, serialize=False)),
                (
                    "contact",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Contact"
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date Création"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmailSend",
            fields=[
                ("id_message", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=50, verbose_name="Nom Client")),
                ("contact", models.CharField(max_length=50, verbose_name="Contact")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email Client"),
                ),
                (
                    "message",
                    models.CharField(max_length=255, verbose_name="Message du Client"),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date Création"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HotelInfo",
            fields=[
                ("id_info", models.AutoField(primary_key=True, serialize=False)),
                ("app_name", models.CharField(max_length=50, verbose_name="Nom Hôtel")),
                (
                    "app_adresse",
                    models.CharField(max_length=50, verbose_name="Adresse Hôtel"),
                ),
                (
                    "app_mailadresse",
                    models.EmailField(max_length=254, verbose_name="Email Hôtel"),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date Création"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LienSocialeCompany",
            fields=[
                ("id_lien", models.AutoField(primary_key=True, serialize=False)),
                (
                    "designation",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Nom de la Plateforme"
                    ),
                ),
                (
                    "lien",
                    models.CharField(
                        max_length=255, verbose_name="lien vers le compte"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NewsLetterEmail",
            fields=[
                ("id_new", models.AutoField(primary_key=True, serialize=False)),
                (
                    "email_visteur",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email visiteur"
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="actif ?")),
            ],
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                ("id_photo", models.AutoField(primary_key=True, serialize=False)),
                ("titre", models.CharField(max_length=100, verbose_name="Titre")),
                ("image", models.ImageField(upload_to="photos/", verbose_name="Image")),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date création"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="plat",
            fields=[
                ("id_plat", models.AutoField(primary_key=True, serialize=False)),
                (
                    "image",
                    models.ImageField(
                        upload_to="Plats_image/", verbose_name="Image plat"
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Nom Plat"
                    ),
                ),
                (
                    "prix",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Prix plat"
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                ("status", models.BooleanField(default=True, verbose_name="Visible ?")),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date Création"
                    ),
                ),
                (
                    "date_update",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2025, 5, 7, 21, 23, 25, 153769, tzinfo=datetime.timezone.utc
                        ),
                        verbose_name="Date Mise à jour",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="reservation",
            fields=[
                ("id_reservation", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nom",
                    models.CharField(max_length=100, verbose_name="Nom-Prénom Client"),
                ),
                (
                    "contact",
                    models.CharField(max_length=50, verbose_name="Contact Client"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email Client"),
                ),
                ("date_arrivee", models.DateField(verbose_name="Date Arrivée")),
                ("date_depart", models.DateField(verbose_name="Date Départ")),
                ("nombre_adulte", models.IntegerField(verbose_name="Nombre d'adultes")),
                ("nombre_enfant", models.IntegerField(verbose_name="Nombre d'enfants")),
                (
                    "message",
                    models.CharField(max_length=255, verbose_name="Message Client"),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date Création"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceClient",
            fields=[
                ("id_agent", models.AutoField(primary_key=True, serialize=False)),
                (
                    "image",
                    models.ImageField(
                        upload_to="Service_Client_image/",
                        verbose_name="Image principal",
                    ),
                ),
                (
                    "image_alt_text",
                    models.CharField(
                        max_length=125,
                        verbose_name="Texte alternatif pour accessibilité de l'image",
                    ),
                ),
                (
                    "nom_complet",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nom Complet"
                    ),
                ),
                (
                    "description",
                    models.EmailField(max_length=254, verbose_name="Description"),
                ),
                (
                    "pinned",
                    models.BooleanField(default=False, verbose_name="Épingler ?"),
                ),
                (
                    "actif",
                    models.BooleanField(default=True, verbose_name="Agent actif ?"),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date Création"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="testimony",
            fields=[
                ("id_testimony", models.AutoField(primary_key=True, serialize=False)),
                (
                    "image",
                    models.ImageField(
                        upload_to="testimony_photos/", verbose_name="Photo Client"
                    ),
                ),
                (
                    "nom_prenom",
                    models.CharField(max_length=100, verbose_name="Nom-Prénom Client"),
                ),
                (
                    "temoignage",
                    models.CharField(max_length=250, verbose_name="Témoignage"),
                ),
                (
                    "visible",
                    models.BooleanField(default=False, verbose_name="Visible ?"),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date Création"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="reservation_chambre",
            fields=[
                ("id_reservation", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nom",
                    models.CharField(max_length=100, verbose_name="Nom-Prénom Client"),
                ),
                (
                    "contact",
                    models.CharField(max_length=50, verbose_name="Contact Client"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email Client"),
                ),
                ("date_arrivee", models.DateField(verbose_name="Date Arrivée")),
                ("date_depart", models.DateField(verbose_name="Date Départ")),
                ("nombre_adulte", models.IntegerField(verbose_name="Nombre d'adultes")),
                ("nombre_enfant", models.IntegerField(verbose_name="Nombre d'enfants")),
                (
                    "message",
                    models.CharField(max_length=255, verbose_name="Message Client"),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date Création"
                    ),
                ),
                (
                    "id_chambre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="nova.chambre"
                    ),
                ),
            ],
        ),
    ]
