# Generated by Django 5.2 on 2025-05-07 21:29

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nova", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chambre",
            name="date_update",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Date Mise à jour"
            ),
        ),
        migrations.AlterField(
            model_name="plat",
            name="date_update",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 5, 7, 21, 29, 23, 864648, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Date Mise à jour",
            ),
        ),
    ]
