# Generated by Django 5.2 on 2025-05-07 21:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nova", "0002_alter_chambre_date_update_alter_plat_date_update"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plat",
            name="date_update",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Date Mise à jour"
            ),
        ),
    ]
