# Generated by Django 5.2 on 2025-05-08 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nova", "0004_chambre_type_chambre_plat_type_plat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceclient",
            name="description",
            field=models.CharField(max_length=255, verbose_name="Description"),
        ),
    ]
