# Generated by Django 5.2 on 2025-05-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nova", "0006_alter_plat_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceclient",
            name="role",
            field=models.CharField(default="Agent", max_length=50, verbose_name="Rôle"),
        ),
        migrations.AlterField(
            model_name="serviceclient",
            name="description",
            field=models.CharField(max_length=255, verbose_name="Rôle"),
        ),
    ]
