# Generated by Django 5.2 on 2025-05-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nova", "0007_serviceclient_role_alter_serviceclient_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="titre",
            field=models.CharField(max_length=255, verbose_name="Titre"),
        ),
        migrations.AlterField(
            model_name="serviceclient",
            name="description",
            field=models.CharField(max_length=255, verbose_name="Description"),
        ),
    ]
