# Generated by Django 5.2 on 2025-05-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nova", "0008_alter_photo_titre_alter_serviceclient_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceclient",
            name="email",
            field=models.EmailField(
                default="johndoe@gmail.com", max_length=254, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="emailsend",
            name="nom",
            field=models.CharField(max_length=100, verbose_name="Client"),
        ),
    ]
