# Generated by Django 5.2 on 2025-05-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nova", "0009_serviceclient_email_alter_emailsend_nom"),
    ]

    operations = [
        migrations.AddField(
            model_name="chambre",
            name="numero_chambre",
            field=models.IntegerField(default=0, verbose_name="Numéro de chambre"),
        ),
    ]
