# Generated by Django 5.2 on 2025-05-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nova", "0010_chambre_numero_chambre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chambre",
            name="numero_chambre",
            field=models.CharField(default="000", verbose_name="Numéro de chambre"),
        ),
    ]
