# Generated by Django 5.2 on 2025-05-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nova", "0011_alter_chambre_numero_chambre"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="is_confirm",
            field=models.BooleanField(default=False, verbose_name="Confirmer ?"),
        ),
        migrations.AddField(
            model_name="reservation_chambre",
            name="is_finish",
            field=models.BooleanField(default=False, verbose_name="Terminer ?"),
        ),
    ]
