# Generated by Django 5.2.5 on 2025-08-13 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nova", "0012_reservation_is_confirm_reservation_chambre_is_finish"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"verbose_name": "Article", "verbose_name_plural": "Articles"},
        ),
        migrations.AlterModelOptions(
            name="chambre",
            options={"verbose_name": "Chambre", "verbose_name_plural": "Chambres"},
        ),
        migrations.AlterModelOptions(
            name="contactcompany",
            options={"verbose_name": "Contact", "verbose_name_plural": "Contacts"},
        ),
        migrations.AlterModelOptions(
            name="emailsend",
            options={"verbose_name": "Mail", "verbose_name_plural": "Mails"},
        ),
        migrations.AlterModelOptions(
            name="hotelinfo",
            options={
                "verbose_name": "Information",
                "verbose_name_plural": "Informations",
            },
        ),
        migrations.AlterModelOptions(
            name="liensocialecompany",
            options={"verbose_name": "Lien", "verbose_name_plural": "Liens"},
        ),
        migrations.AlterModelOptions(
            name="newsletteremail",
            options={"verbose_name": "Abonné", "verbose_name_plural": "Abonnés"},
        ),
        migrations.AlterModelOptions(
            name="photo",
            options={"verbose_name": "Image", "verbose_name_plural": "Images"},
        ),
        migrations.AlterModelOptions(
            name="plat",
            options={"verbose_name": "Plat", "verbose_name_plural": "Plats"},
        ),
        migrations.AlterModelOptions(
            name="reservation",
            options={
                "verbose_name": "Réservation",
                "verbose_name_plural": "Réservations",
            },
        ),
        migrations.AlterModelOptions(
            name="reservation_chambre",
            options={
                "verbose_name": "Réservation Chambre",
                "verbose_name_plural": "Réservations de chambre",
            },
        ),
        migrations.AlterModelOptions(
            name="serviceclient",
            options={"verbose_name": "Service", "verbose_name_plural": "Services"},
        ),
        migrations.AlterModelOptions(
            name="testimony",
            options={
                "verbose_name": "Témoignage",
                "verbose_name_plural": "Témoignages",
            },
        ),
        migrations.AlterField(
            model_name="reservation_chambre",
            name="id_chambre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                related_query_name="reservation",
                to="nova.chambre",
            ),
        ),
    ]
